---
- name: Install Docker and run container
  hosts: remote_hosts
  become: true  # Use sudo to run commands
  tasks:

    # Install Docker (Debian/Ubuntu-based systems)
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    # Start Docker service
    - name: Ensure Docker service is started and enabled
      service:
        name: docker
        state: started
        enabled: yes

    - name: Remove any existing hn-score-prediction container
      docker_container:
        name: hn-score-prediction-container
        state: absent

    # Run the container from the pulled image
    - name: Run hn-score-prediction container
      docker_container:
        name: hn-score-prediction-container
        image: 12v12v/hn-score-prediction
        state: started
        restart_policy: always
        pull: true
        published_ports:
          - "8000:60606"
        network_mode: bridge
